#!/bin/bash

# Auto-Build Environment Setup
# Spec: 002-load-user-data-with-local-trip-based-events
# Generated by Planner Agent

set -e

echo "========================================"
echo "FitTravel Flutter Development Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# PREREQUISITES CHECK
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Flutter is installed
if ! command -v flutter &> /dev/null; then
    echo -e "${RED}Flutter is not installed. Please install Flutter first.${NC}"
    echo "Visit: https://docs.flutter.dev/get-started/install"
    exit 1
fi
echo -e "${GREEN}✓ Flutter found${NC}"

# Check Dart is available
if ! command -v dart &> /dev/null; then
    echo -e "${RED}Dart is not available. Ensure Flutter is properly installed.${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Dart found${NC}"

# ============================================
# PROJECT SETUP
# ============================================

echo ""
echo "Setting up project dependencies..."

# Get Flutter dependencies
flutter pub get

echo -e "${GREEN}✓ Dependencies installed${NC}"

# ============================================
# STATIC ANALYSIS
# ============================================

echo ""
echo "Running static analysis..."

dart analyze lib/

echo -e "${GREEN}✓ Static analysis complete${NC}"

# ============================================
# ENVIRONMENT CONFIGURATION
# ============================================

echo ""
echo "========================================"
echo "Environment Configuration"
echo "========================================"
echo ""
echo "To run the app with all features, provide these environment variables:"
echo ""
echo "  flutter run \\"
echo "    --dart-define=GOOGLE_PLACES_API_KEY=your_key \\"
echo "    --dart-define=SUPABASE_FUNCTIONS_BASE_URL=https://your-project.functions.supabase.co \\"
echo "    --dart-define=SUPABASE_ANON_KEY=your_anon_key"
echo ""

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Quick commands:"
echo "  flutter run                    # Run on default device"
echo "  flutter run -d chrome          # Run on Chrome"
echo "  flutter test                   # Run all tests"
echo "  dart analyze lib/              # Static analysis"
echo ""
echo "Project Structure:"
echo "  lib/services/                  # Business logic services"
echo "  lib/models/                    # Data models"
echo "  lib/screens/                   # UI screens"
echo "  test/                          # Test files"
echo ""
